POST http://127.0.0.1:5000/perform_query
Accept: application/json
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "regex",
  "value1": "images/\\w+\\.png",
  "cmd2": "sort",
  "value2": "asc"
}


###
POST http://127.0.0.1:5000/perform_query
Accept: application/json
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "filter",
  "value1": "GET",
  "cmd2": "map",
  "value2": "0"
}


###
POST http://127.0.0.1:5000/perform_query
Accept: application/json
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "6",
  "cmd2": "limit",
  "value2": "4"
}


###
POST http://127.0.0.1:80/perform_query
Accept: application/json
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "6",
  "cmd2": "limit",
  "value2": "4"
}

###
GET http://127.0.0.1:80
#Accept: text/html